---
logs:
  - type: file
    path: /var/log/haproxy/*.log
    service: haproxy
    source: haproxy
    sourcecategory: http_web_access

init_config:
instances:
  - url: http://localhost/haproxy_adm_panel?stats
    username: admin
    password: my_awesome_password
    collect_status_metrics: true
