---
logs:
  - type: file
    path: /var/log/haproxy/haproxy.log
    service: jahia
    source: haproxy
    sourcecategory: http_web_access
  - type: file
    path: /var/log/haproxy/haproxy-status.log
    service: jahia
    source: haproxy
    sourcecategory: haproxy_status

init_config:
instances:
  - url: http://localhost/haproxy_adm_panel?stats
    username: admin
    password: my_awesome_password
    collect_status_metrics: true
    enable_service_check: true
    status_check: true

